spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ??? ?? ??/???? (???)
    show-sql: true      # SQL ?? ?? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL ??

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

server:
  port: 19098

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    secret-key: 401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1
    refresh: refresh_token

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

