spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ??? ?? ??/???? (???)
    show-sql: true      # SQL ?? ?? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL ??

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 19092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    secret-key: ${JWT_KEY}
