
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hub
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    open-in-view: false

  sql:
    init:
      mode: always

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass
server:
  port: 8082

kakao:
  api:
    key: ${KAKAO_KEY}