spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/order?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: { $username }
    password: { $password }
    driver-class-name: { $database_driver }

  jpa:
    database: { $database }
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: { $database_host }
      port: { $database_port }


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:19090/eureka/


#  jackson:
#    serialization:
#      WRITE_DATES_AS_TIMESTAMPS: false  # ISO-8601 형식으로 날짜를 저장
#    default-property-inclusion: non_null

