server:
  port: 8083

spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/item
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    open-in-view: false

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

kafka:
  server:
    url: localhost:9092