

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/total/**, /slack/**
      discovery:
        locator:
          enabled: true
  data:
    redis:
      host: localhost
      port: 6379


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 19091

service:
  jwt:
    secret-key: ${JWT_KEY}
    issuer: user-service
    refresh: refresh_token
    black-list: black_list