spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/total/**, /slack/**
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/hubs/**
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/stores/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/deliveries/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
      discovery:
        locator:
          enabled: true
  data:
    redis:
      host: localhost
      port: 6379


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 19091

service:
  jwt:
    secret-key: ${JWT_KEY}
    issuer: user-service
    refresh: refresh_token
    black-list: black_list


management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0