spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:mysql://localhost:3306/delivery
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    bootstrap-servers: localhost:9092
  jpa:
    hibernate:
      ddl-auto: update  # ?????? ??? ?? ?? ? ????
      show_sql: true    # ???? SQL ?? ?? ??
      format_sql: true  # SQL ?? ???
    properties:
      hibernate:
        default_batch_fetch_size: 100


server:
  port: 19096
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    fetch-registry: true
    register-with-eureka: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0