version: '3.8'

services:
  user:
    build: .
    container_name: user_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/app  # 로컬 소스 코드를 컨테이너에 마운트

  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: